export const UI_DICT: Record<string, string> = {
  "/ 1.0": "/ ১.০",
  "/ kg": "/ কেজি",
  "/kg": "/কেজি",
  "% (Max": "% (সর্বোচ্চ",
  "• Period:": "• সময়কাল:",
  "↓ Dedicated Highway Transit Corridor": "↓ ডেডিকেটেড হাইওয়ে ট্রানজিট করিডোর",
  "+880 17XX-XXXXXX or NID": "+৮৮০ ১৭XX-XXXXXX বা এনআইডি",
  "1. User Mgmt": "১. ইউজার ব্যবস্থাপনা",
  "10 Admin Modules": "১০টি এডমিন মডিউল",
  "10. Land Audit": "১০. ভূমি নিরীক্ষা",
  "100% gateway uptime": "১০০% গেটওয়ে আপটাইম",
  "16 Farmer Modules": "১৬টি কৃষক মডিউল",
  "17-digit or 10-digit smart NID": "১৭-অঙ্ক বা ১০-অঙ্কের স্মার্ট এনআইডি",
  "2. Marketplace": "২. মার্কেটপ্লেস",
  "3. Orders": "৩. অর্ডার",
  "4 Active": "৪টি সক্রিয়",
  "4. Payments": "৪. পেমেন্ট",
  "5. Quality Mgmt": "৫. মান ব্যবস্থাপনা",
  "6,140 commercial plots": "৬,১৪০টি বাণিজ্যিক প্লট",
  "6. Logistics": "৬. লজিস্টিকস",
  "7. Training": "৭. প্রশিক্ষণ",
  "8. Reports": "৮. রিপোর্ট",
  "9. Disputes": "৯. বিবাদ",
  "98.4% Active": "৯৮.৪% সক্রিয়",
  "About AgriNova": "FarmPath সম্পর্কে",
  "Account Status": "অ্যাকাউন্ট অবস্থা",
  "Acreage:": "জমির পরিমাণ:",
  "Acres": "একর",
  "Acres)": "একর)",
  "Across 8 administrative divisions": "৮টি প্রশাসনিক বিভাগ জুড়ে",
  "Across licensed silos": "লাইসেন্সপ্রাপ্ত সাইলোতে",
  "Across scheduled freights": "নির্ধারিত পরিবহনে",
  "Action": "কর্ম",
  "Action Type": "কর্মের ধরন",
  "Actionable Field Protocol": "কার্যকর মাঠ প্রোটোকল",
  "Actions": "কর্ম",
  "Active": "সক্রিয়",
  "Active Cargo Volume": "সক্রিয় কার্গো ভলিউম",
  "Active farmer accounts": "সক্রিয় কৃষক অ্যাকাউন্ট",
  "Active Hearings:": "সক্রিয় শুনানি:",
  "Active highway dispatches": "সক্রিয় হাইওয়ে ডিসপ্যাচ",
  "Active in Transit": "পথে সক্রিয়",
  "Active on Buyer Board": "ক্রেতা বোর্ডে সক্রিয়",
  "Active Plots": "সক্রিয় প্লট",
  "Actor & Role": "কর্তা ও ভূমিকা",
  "Add Farm": "খামার যোগ",
  "Add Field": "ক্ষেত যোগ",
  "Add Master Crop": "মাস্টার ফসল যোগ",
  "Adjust Rate": "দর সমন্বয়",
  "Admin Operational Command Matrix (10 Core Modules)": "এডমিন অপারেশনাল কমান্ড ম্যাট্রিক্স (১০টি মূল মডিউল)",
  "Administered floor prices, wholesale modal averages, and trading volume across primary district mokams.": "প্রধান জেলা মোকামে সরকারি ফ্লোর মূল্য, পাইকারি মোডাল গড় ও লেনদেন ভলিউম।",
  "Advisory (Information / Caution)": "পরামর্শ (তথ্যমূলক / সতর্কতা)",
  "Advisory bulletin expired": "পরামর্শ বুলেটিনের মেয়াদ শেষ",
  "Advisory Category": "পরামর্শের বিভাগ",
  "Advisory Expiration Window": "পরামর্শের মেয়াদ শেষ হওয়ার সময়",
  "Advisory published to farmer networks & SMS gateway": "কৃষক নেটওয়ার্ক ও এসএমএস গেটওয়েতে পরামর্শ প্রকাশিত হয়েছে",
  "Advisory Title": "পরামর্শের শিরোনাম",
  "Aflatoxin (Safety)": "অ্যাফ্লাটক্সিন (নিরাপত্তা)",
  "Aflatoxin Mycotoxin Level:": "অ্যাফ্লাটক্সিন মাইকোটক্সিনের মাত্রা:",
  "Agribusiness": "এগ্রিবিজনেস",
  "Agricultural Datasets": "কৃষি ডেটাসেট",
  "Agricultural Extension & Farmer Academy": "কৃষি এক্সটেনশন ও কৃষক একাডেমি",
  "Agronomic Advisory & Pest Warning Control": "কৃষি পরামর্শ ও কীট সতর্কতা নিয়ন্ত্রণ",
  "Agronomic Advisory Details": "কৃষি পরামর্শের বিবরণ",
  "Agronomic Category": "কৃষি বিভাগ",
  "Agronomic Synthesis & Rationale": "কৃষি সিন্থেসিস ও যৌক্তিকতা",
  "Agronomic Target": "কৃষি লক্ষ্য",
  "Agronomist (Advisory)": "কৃষিবিদ (পরামর্শ)",
  "Agronomists": "কৃষিবিদ",
  "Agronomy": "কৃষিতত্ত্ব",
  "AI Agriculture Assistant": "এআই কৃষি সহকারী",
  "AI Soil & Crop Diagnostic Synthesis": "এআই মাটি ও ফসল ডায়াগনস্টিক সিন্থেসিস",
  "Alert Headline": "সতর্কতা শিরোনাম",
  "All Arbitration Statuses": "সব সালিশি অবস্থা",
  "All bank & mobile channels": "সব ব্যাংক ও মোবাইল চ্যানেল",
  "All Categories": "সব বিভাগ",
  "All Categories (": "সব বিভাগ (",
  "All Compliance Verdicts": "সব কমপ্লায়েন্স রায়",
  "All Escrow Statuses": "সব এসক্রো অবস্থা",
  "All Intelligence Categories": "সব বুদ্ধিমত্তা বিভাগ",
  "All Listing Statuses": "সব তালিকা অবস্থা",
  "All notifications marked as read": "সব বিজ্ঞপ্তি পড়া হিসেবে চিহ্নিত হয়েছে",
  "All Payout Statuses": "সব পেমেন্ট অবস্থা",
  "All Requests": "সব অনুরোধ",
  "All Roles": "সব ভূমিকা",
  "All Severities": "সব তীব্রতা",
  "All Statuses": "সব অবস্থা",
  "All Transit Statuses": "সব ট্রানজিট অবস্থা",
  "Allegation:": "অভিযোগ:",
  "Already have an account?": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
  "Analytics and reports will be displayed here.": "বিশ্লেষণ ও রিপোর্ট এখানে প্রদর্শিত হবে।",
  "Application Window:": "প্রয়োগের সময়:",
  "Apply this fertilizer regimen directly to your field batch or compare against alternative winter crops.": "এই সার পদ্ধতি সরাসরি আপনার ক্ষেতে প্রয়োগ করুন অথবা বিকল্প শীতকালীন ফসলের সাথে তুলনা করুন।",
  "Approve": "অনুমোদন",
  "Approve & Certify": "অনুমোদন ও সার্টিফাই",
  "Approve for Trading": "ট্রেডিংয়ের জন্য অনুমোদন",
  "Approved": "অনুমোদিত",
  "Approved Cultivars": "অনুমোদিত জাত",
  "Approved Listings": "অনুমোদিত তালিকা",
  "Approved Varieties (comma-separated)": "অনুমোদিত জাত (কমা দ্বারা পৃথক)",
  "Arbitration Assessment & Escrow Order": "সালিশি মূল্যায়ন ও এসক্রো আদেশ",
  "Archived": "আর্কাইভড",
  "are in healthy condition. Ideal sunny day for irrigation.": "সুস্থ অবস্থায় আছে। সেচের জন্য আদর্শ রোদেলা দিন।",
  "Area": "আয়তন",
  "Ask me anything about agriculture, crops, or the platform!": "কৃষি, ফসল বা প্ল্যাটফর্ম সম্পর্কে যেকোনো প্রশ্ন করুন!",
  "Asking Price:": "প্রার্থীত মূল্য:",
  "Asking Rate:": "প্রার্থীত দর:",
  "Assigned Grade:": "নির্ধারিত গ্রেড:",
  "Assigned Lead Instructor": "নিয়োজিত প্রধান প্রশিক্ষক",
  "Attached Evidence & Land Revenue Receipts": "সংযুক্ত প্রমাণ ও ভূমি রাজস্ব রশিদ",
  "Audit": "নিরীক্ষা",
  "Audit Deeds & Review": "দলিল নিরীক্ষা ও রিভিউ",
  "Audit digital payouts to farmers, freight carriers, and testing labs via BEFTN, bKash, and Nagad channels.": "বিইএফটিএন, বিকাশ ও নগদ চ্যানেলে কৃষক, মালবাহী ক্যারিয়ার ও পরীক্ষণ ল্যাবের ডিজিটাল পেমেন্ট নিরীক্ষা করুন।",
  "Audit farmer bulk crop listings, regulate floor/ceiling price bands, and moderate trade catalogs.": "কৃষকের পাইকারি ফসল তালিকা নিরীক্ষা, মূল্য সীমা নিয়ন্ত্রণ ও ট্রেড ক্যাটালগ মডারেট করুন।",
  "Audit farmer land tenure records, Porcha deeds, and Union cadastral map plots for DAE certification.": "ডিএই ই সার্টিফিকেশনের জন্য কৃষকের জমির অধিকার রেকর্ড, পর্চা দলিল ও ইউনিয়ন ক্যাডাস্ট্রাল ম্যাপ যাচাই করুন।",
  "Audit Record →": "নিরীক্ষা রেকর্ড →",
  "Audit Timestamp": "নিরীক্ষা টাইমস্ট্যাম্প",
  "Audit Verifications (": "নিরীক্ষা যাচাই (",
  "Auditor Endorsement / Rejection Remarks": "নিরীক্ষকের অনুমোদন / প্রত্যাখ্যান মন্তব্য",
  "Auditor Notes (": "নিরীক্ষক নোট (",
  "Autumn": "শরৎ",
  "Available Volume:": "উপলব্ধ পরিমাণ:",
  "Awaiting Authorization": "অনুমোদন অপেক্ষমাণ",
  "Awaiting compliance": "কমপ্লায়েন্স অপেক্ষমাণ",
  "Awaiting officer audit": "অফিসার নিরীক্ষা অপেক্ষমাণ",
  "Backend Sync: Simulated Live": "ব্যাকএন্ড সিঙ্ক: সিমুলেটেড লাইভ",
  "Bangladesh Digital Agriculture Platform • Secure Multi-Role Authentication System": "বাংলাদেশ ডিজিটাল কৃষি প্ল্যাটফর্ম • নিরাপদ মাল্টি-রোল অথেনটিকেশন সিস্টেম",
  "Batch:": "ব্যাচ:",
  "BDT": "৳",
  "BEFTN & bKash Payouts": "বিইএফটিএন ও বিকাশ পেমেন্ট",
  "Benchmark Price": "বেঞ্চমার্ক দাম",
  "bKash, BEFTN, Nagad, Rocket": "বিকাশ, বিইএফটিএন, নগদ, রকেট",
  "Blight or excessive moisture": "ব্লাইট বা অতিরিক্ত আর্দ্রতা",
  "BMD Sat-Link Active": "বিএমডি স্যাট-লিংক সক্রিয়",
  "Boro, Potato & Mustard": "বোরো, আলু ও সরিষা",
  "Botanical / Scientific Name": "উদ্ভিদতাত্ত্বিক / বৈজ্ঞানিক নাম",
  "Broadcast emergency blight notices, fertilization timing, and water management bulletins.": "জরুরি ব্লাইট বিজ্ঞপ্তি, সার প্রয়োগের সময় ও পানি ব্যবস্থাপনা বুলেটিন সম্প্রচার করুন।",
  "Browse agricultural tools": "কৃষি সরঞ্জাম দেখুন",
  "Browse available seeds": "উপলব্ধ বীজ দেখুন",
  "Browse fertilizers": "সার দেখুন",
  "Buy seeds, fertilizers, and agricultural supplies": "বীজ, সার ও কৃষি সরবরাহ কিনুন",
  "Buyer": "ক্রেতা",
  "Buyer Institution:": "ক্রেতা প্রতিষ্ঠান:",
  "Buyer vs Farmer": "ক্রেতা বনাম কৃষক",
  "by": "দ্বারা",
  "By:": "দ্বারা:",
  "Cadastral Deeds": "ক্যাডাস্ট্রাল দলিল",
  "Cadastral Plot Nos.": "ক্যাডাস্ট্রাল প্লট নম্বর",
  "Calculated to correct soil deficiencies over 90-day growth cycle": "৯০ দিনের বৃদ্ধি চক্রে মাটির ঘাটতি পূরণের জন্য গণনাকৃত",
  "Cancel": "বাতিল",
  "Cargo Weight": "কার্গো ওজন",
  "Carrier / Fleet:": "ক্যারিয়ার / বহর:",
  "Cases": "মামলা",
  "Cash Crop": "নগদ ফসল",
  "center.": "কেন্দ্র।",
  "Central Agronomy & Platform Governance Network": "কেন্দ্রীয় কৃষিতত্ত্ব ও প্ল্যাটফর্ম পরিচালনা নেটওয়ার্ক",
  "Cereal": "শস্য",
  "Cert:": "সার্ট:",
  "Certified Grade:": "সার্টিফাইড গ্রেড:",
  "Certifying Lab:": "সার্টিফায়িং ল্যাব:",
  "Close": "বন্ধ",
  "Close Audit": "নিরীক্ষা বন্ধ",
  "Close dialog": "ডায়ালগ বন্ধ করুন",
  "Close drawer": "ড্রয়ার বন্ধ করুন",
  "Cold Chain & GPS Fleet": "কোল্ড চেইন ও জিপিএস বহর",
  "Cold Chain Integrity": "কোল্ড চেইন অখণ্ডতা",
  "Commodity modal price updated on public board": "পণ্যের মোডাল মূল্য পাবলিক বোর্ডে আপডেট করা হয়েছে",
  "Compare Other Crops": "অন্য ফসলের সাথে তুলনা",
  "Compiling live data into automated Q3 DAE Ministry Briefing...": "লাইভ ডেটা স্বয়ংক্রিয় তৃতীয় ত্রৈমাসিক ডিএই ই মন্ত্রণালয় ব্রিফিংয়ে সংকলন করা হচ্ছে...",
  "Complainant (Plaintiff):": "বাদী:",
  "Completed": "সম্পন্ন",
  "Completion Progress": "সম্পন্নের অগ্রগতি",
  "Completion Rate": "সম্পন্নের হার",
  "Compliance Verdict:": "কমপ্লায়েন্স রায়:",
  "Compose Agronomic Bulletin": "কৃষি বুলেটিন তৈরি করুন",
  "Compose and broadcast immediate microclimate advisory": "তাৎক্ষণিক মাইক্রোক্লাইমেট পরামর্শ তৈরি ও সম্প্রচার করুন",
  "Conditional Pass": "শর্তসাপেক্ষ পাস",
  "Connecting farmers with buyers through technology": "প্রযুক্তির মাধ্যমে কৃষক ও ক্রেতার সংযোগ",
  "Consignment Weight:": "কনসাইনমেন্ট ওজন:",
  "Contact Details": "যোগাযোগের তথ্য",
  "Contact Us": "যোগাযোগ করুন",
  "Contract Value": "চুক্তি মূল্য",
  "Contracts & Escrow": "চুক্তি ও এসক্রো",
  "Core Agro-Statistical Insights": "মূল কৃষি-পরিসংখ্যান অন্তর্দৃষ্টি",
  "Could not update task": "কাজ আপডেট করা যায়নি",
  "Countermeasure:": "প্রতিরোধমূলক ব্যবস্থা:",
  "Create Account": "অ্যাকাউন্ট তৈরি",
  "Create an authorized identity for platform services": "প্ল্যাটফর্ম সেবার জন্য অনুমোদিত পরিচয় তৈরি করুন",
  "Create Crop Batch": "ফসল ব্যাচ তৈরি",
  "Create Harvest Lot": "হার্ভেস্ট লট তৈরি",
  "Create Lot": "লট তৈরি",
  "Create New Course Curriculum": "নতুন কোর্স কারিকুলাম তৈরি",
  "Critical (Severe Flash Flood / Cyclone)": "গুরুতর (মারাত্মক আকস্মিক বন্যা / ঘূর্ণিঝড়)",
  "Crop activity log saved to permanent audit ledger": "ফসলের কার্যকলাপ লগ স্থায়ী নিরীক্ষা লেজারে সংরক্ষিত হয়েছে",
  "Crop batch sown & registered": "ফসল ব্যাচ বপন ও নিবন্ধিত হয়েছে",
  "Crop Cycle Details": "ফসল চক্রের বিবরণ",
  "Crop cycle details will be displayed here.": "ফসল চক্রের বিবরণ এখানে প্রদর্শিত হবে।",
  "Crop Cycles": "ফসল চক্র",
  "Crop Details": "ফসলের বিবরণ",
  "Crop details will be displayed here.": "ফসলের বিবরণ এখানে প্রদর্শিত হবে।",
  "crop fields": "ফসলি ক্ষেত",
  "Crop Name": "ফসলের নাম",
  "Crop Yield Index": "ফসল ফলন সূচক",
  "Cryptographically sealed timeline of administrative approvals, credential changes, and broadcast events.": "প্রশাসনিক অনুমোদন, পরিচয়পত্র পরিবর্তন ও সম্প্রচার ইভেন্টের ক্রিপ্টোগ্রাফিকভাবে সিল করা টাইমলাইন।",
  "Cultivar:": "জাত:",
  "Current season acreage breakdown by cereal, oilseed, and pulse": "শস্য, তেলবীজ ও ডাল অনুযায়ী বর্তমান মৌসুমের জমির বণ্টন",
  "Current Sensor Level": "বর্তমান সেন্সর মাত্রা",
  "Currently transmitting to field officers, farmer portals, and regional SMS gateways": "বর্তমানে ফিল্ড অফিসার, কৃষক পোর্টাল ও আঞ্চলিক এসএমএস গেটওয়েতে প্রেরণ হচ্ছে",
  "Curriculum Title": "কারিকুলামের শিরোনাম",
  "DAE certified laboratory testing records: Moisture threshold compliance, foreign matter, and aflatoxin safety.": "ডিএই ই সার্টিফাইড ল্যাবরেটরি পরীক্ষার রেকর্ড: আর্দ্রতা থ্রেশহোল্ড কমপ্লায়েন্স, বিদেশি ময়লা ও অ্যাফ্লাটক্সিন নিরাপত্তা।",
  "DAE Course Workshops": "ডিএই ই কোর্স ওয়ার্কশপ",
  "DAE official agronomic taxon baseline": "ডিএই ই-র অফিসিয়াল কৃষি ট্যাক্সন বেসলাইন",
  "DAE Verified Agronomist Certificate of Completion": "ডিএই ই-যাচাইকৃত কৃষিবিদ সমাপ্তি সার্টিফিকেট",
  "DAE-certified agronomic masterclasses, soil nutrition guides, and high-efficiency water conservation techniques.": "ডিএই ই-সার্টিফাইড কৃষি মাস্টারক্লাস, মাটি পুষ্টি গাইড ও উচ্চ-দক্ষ পানি সংরক্ষণ কৌশল।",
  "DAM Feed: Synchronized Today": "ডিএএম ফিড: আজ সিঙ্ক্রোনাইজ হয়েছে",
  "Dataset management will be displayed here.": "ডেটাসেট ব্যবস্থাপনা এখানে প্রদর্শিত হবে।",
  "Days": "দিন",
  "Deadline": "সময়সীমা",
  "Deeds attached": "দলিল সংযুক্ত",
  "Defendant:": "বিবাদী:",
  "Deficiency Status": "ঘাটতির অবস্থা",
  "Delayed": "বিলম্বিত",
  "Delivered": "ডেলিভারড",
  "Deliveries": "ডেলিভারি",
  "Demand Board": "চাহিদা বোর্ড",
  "Demand Details": "চাহিদার বিবরণ",
  "Demand details will be displayed here.": "চাহিদার বিবরণ এখানে প্রদর্শিত হবে।",
  "Deploy Now": "এখন ডিপ্লয় করুন",
  "Describe climatic conditions, pest vectors, and early symptoms...": "জলবায়ু পরিস্থিতি, কীটের বাহক ও প্রাথমিক লক্ষণ বর্ণনা করুন...",
  "Designated Platform Role": "নির্ধারিত প্ল্যাটফর্ম ভূমিকা",
  "Detailed Analytics": "বিস্তারিত বিশ্লেষণ",
  "Details": "বিস্তারিত",
  "Digitally secured": "ডিজিটালভাবে সুরক্ষিত",
  "Direct Channels": "ডাইরেক্ট চ্যানেল",
  "Direct executive access to all platform oversight, marketplace, and logistics subsystems": "সব প্ল্যাটফর্ম তত্ত্বাবধান, মার্কেটপ্লেস ও লজিস্টিক সাবসিস্টেমে নির্বাহীর সরাসরি প্রবেশাধিকার",
  "Disbursement Amount": "বিতরণকৃত পরিমাণ",
  "Dismiss bulletin": "বুলেটিন বাতিল",
  "Dismissed": "খারিজ",
  "Dispatched": "প্রেরিত",
  "Disputed": "বিবাদিত",
  "Disputed Escrow Fund:": "বিবাদিত এসক্রো তহবিল:",
  "Disputed Orders": "বিবাদিত অর্ডার",
  "distinct farm parcels covering": "টি আলাদা খামার প্লট",
  "Districts:": "জেলা:",
  "Document Size:": "ডকুমেন্ট সাইজ:",
  "Documentation": "ডকুমেন্টেশন",
  "Download PDF": "পিডিএফ ডাউনলোড",
  "Draft (Under Review)": "ড্রাফট (রিভিউ চলমান)",
  "Driver:": "চালক:",
  "e.g. Barind Tract & Drought-Prone Northwest": "যেমন: বরেন্দ্র অঞ্চল ও খরা-প্রবণ উত্তর-পশ্চিম",
  "e.g. Clay Loam / Sandy Alluvium": "যেমন: এঁটেল দোআঁশ / বেলে পলি",
  "e.g. Dr. Shahinur Alam (BARI)": "যেমন: ড. শাহিনুর আলম (বারি)",
  "e.g. Dr. Shamsul Huda": "যেমন: ড. শামসুল হুদা",
  "e.g. Garidaha, Sherpur, Bogura": "যেমন: গাড়ীদহ, শেরপুর, বগুড়া",
  "e.g. Karatoya South Agro Farm": "যেমন: করতোয়া সাউথ এগ্রো খামার",
  "e.g. Maize (Corn)": "যেমন: ভুট্টা (কর্ন)",
  "e.g. Modern Alternate Wetting and Drying (AWD) Irrigation Protocol": "যেমন: আধুনিক অল্টারনেট ওয়েটিং অ্যান্ড ড্রাইং (এইডব্লিউডি) সেচ প্রোটোকল",
  "e.g. Rabi (Winter)": "যেমন: রবি (শীত)",
  "e.g. REC-84920": "যেমন: আরইসি-৮৪৯২০",
  "e.g. Rice Blast Fungicide Alert": "যেমন: চাল ব্লাস্ট ছত্রাকনাশক সতর্কতা",
  "e.g. Severe Nor'wester (Kalbaishakhi) Storm Warning": "যেমন: তীব্র কালবৈশাখী ঝড় সতর্কতা",
  "e.g. Solar Tube Well / Karatoya Canal": "যেমন: সোলার টিউবওয়েল / করতোয়া খাল",
  "e.g. Tomorrow 18:00 BST": "যেমন: আগামীকাল ১৮:০০ বিএসটি",
  "e.g. Zea mays": "যেমন: জিয়া মেইজ",
  "Email": "ইমেইল",
  "Email Address": "ইমেইল ঠিকানা",
  "Emergency Weather Alert": "জরুরি আবহাওয়া সতর্কতা",
  "En Route": "পথে",
  "Enrolled Farmers": "নিবন্ধিত কৃষক",
  "Enrolled Farmers:": "নিবন্ধিত কৃষক:",
  "Enter your email": "আপনার ইমেইল লিখুন",
  "entries": "এন্ট্রি",
  "Escrow Arbitration": "এসক্রো সালিশি",
  "Escrow hold adjusted": "এসক্রো হোল্ড সমন্বয়কৃত",
  "Escrow paused": "এসক্রো স্থগিত",
  "Escrow State": "এসক্রো অবস্থা",
  "ETA:": "ইটিএ:",
  "Event Details": "ঘটনার বিবরণ",
  "Evidences Attached:": "সংযুক্ত প্রমাণ:",
  "Executive Agricultural Oversight Portal": "নির্বাহী কৃষি তত্ত্বাবধান পোর্টাল",
  "Executive Briefing:": "নির্বাহী ব্রিফিং:",
  "Expense recorded successfully": "ব্যয় সফলভাবে রেকর্ড হয়েছে",
  "Expires:": "মেয়াদ শেষ:",
  "Export Compliance Audit CSV": "কমপ্লায়েন্স অডিট সিএসভি এক্সপোর্ট",
  "Export Full 28-Page Dossier": "সম্পূর্ণ ২৮ পৃষ্ঠার ডসিয়ার এক্সপোর্ট",
  "Export Lab Certificates": "ল্যাব সার্টিফিকেট এক্সপোর্ট",
  "Export Ledger": "লেজার এক্সপোর্ট",
  "Extension Officer (DAE Field Officer)": "এক্সটেনশন অফিসার (ডিএই ই ফিল্ড অফিসার)",
  "Extension Officers": "এক্সটেনশন অফিসার",
  "Failed": "ব্যর্থ",
  "Failed Reversals": "ব্যর্থ রিভার্সাল",
  "Failed to add calendar task": "ক্যালেন্ডার টাস্ক যোগ করা যায়নি",
  "Failed to add crop to registry": "রেজিস্ট্রিতে ফসল যোগ করা যায়নি",
  "Failed to authorize payout disbursement": "পেমেন্ট বিতরণ অনুমোদন করা যায়নি",
  "Failed to broadcast advisory": "পরামর্শ সম্প্রচার করা যায়নি",
  "Failed to create farm": "খামার তৈরি করা যায়নি",
  "Failed to create field": "ক্ষেত তৈরি করা যায়নি",
  "Failed to fetch farmer profile": "কৃষক প্রোফাইল সংগ্রহ করা যায়নি",
  "Failed to load administrative training catalog": "প্রশাসনিক প্রশিক্ষণ ক্যাটালগ লোড করা যায়নি",
  "Failed to load agricultural calendar tasks": "কৃষি ক্যালেন্ডার টাস্ক লোড করা যায়নি",
  "Failed to load agricultural training catalog": "কৃষি প্রশিক্ষণ ক্যাটালগ লোড করা যায়নি",
  "Failed to load agronomic advisories": "কৃষি পরামর্শ লোড করা যায়নি",
  "Failed to load arbitration dispute cases": "সালিশি বিবাদ মামলা লোড করা যায়নি",
  "Failed to load central admin telemetry": "কেন্দ্রীয় এডমিন টেলিমেট্রি লোড করা যায়নি",
  "Failed to load cold chain logistics telemetry": "কোল্ড চেইন লজিস্টিক টেলিমেট্রি লোড করা যায়নি",
  "Failed to load comparison data": "তুলনার ডেটা লোড করা যায়নি",
  "Failed to load crop activity logs": "ফসলের কার্যকলাপ লগ লোড করা যায়নি",
  "Failed to load crop batches": "ফসল ব্যাচ লোড করা যায়নি",
  "Failed to load executive agronomic reports": "নির্বাহী কৃষি রিপোর্ট লোড করা যায়নি",
  "Failed to load expense ledger": "ব্যয় লেজার লোড করা যায়নি",
  "Failed to load farm verification requests": "খামার যাচাইয়ের অনুরোধ লোড করা যায়নি",
  "Failed to load farms": "খামার লোড করা যায়নি",
  "Failed to load fields": "ক্ষেত লোড করা যায়নি",
  "Failed to load harvest records": "হার্ভেস্ট রেকর্ড লোড করা যায়নি",
  "Failed to load laboratory quality inspection certificates": "ল্যাবরেটরি মান পরিদর্শন সার্টিফিকেট লোড করা যায়নি",
  "Failed to load master crop registry": "মাস্টার ফসল রেজিস্ট্রি লোড করা যায়নি",
  "Failed to load meteorological broadcasts": "আবহাওয়াবিদ্যাগত সম্প্রচার লোড করা যায়নি",
  "Failed to load platform analytics telemetry": "প্ল্যাটফর্ম বিশ্লেষণ টেলিমেট্রি লোড করা যায়নি",
  "Failed to load platform payment disbursement records": "প্ল্যাটফর্ম পেমেন্ট বিতরণ রেকর্ড লোড করা যায়নি",
  "Failed to load profitability telemetry": "মুনাফা টেলিমেট্রি লোড করা যায়নি",
  "Failed to load user accounts": "ইউজার অ্যাকাউন্ট লোড করা যায়নি",
  "Failed to load wholesale market indices": "পাইকারি বাজার সূচক লোড করা যায়নি",
  "Failed to load wholesale marketplace listings": "পাইকারি মার্কেটপ্লেস তালিকা লোড করা যায়নি",
  "Failed to load wholesale orders": "পাইকারি অর্ডার লোড করা যায়নি",
  "Failed to mark all as read": "সবগুলো পড়া হিসেবে চিহ্নিত করা যায়নি",
  "Failed to publish training course": "প্রশিক্ষণ কোর্স প্রকাশ করা যায়নি",
  "Failed to record expense": "ব্যয় রেকর্ড করা যায়নি",
  "Failed to record harvest lot": "হার্ভেস্ট লট রেকর্ড করা যায়নি",
  "Failed to register crop batch": "ফসল ব্যাচ নিবন্ধন করা যায়নি",
  "Failed to retrieve AI agronomic diagnostic": "এআই কৃষি ডায়াগনস্টিক সংগ্রহ করা যায়নি",
  "Failed to retrieve immutable security logs": "অপরিবর্তনীয় নিরাপত্তা লগ সংগ্রহ করা যায়নি",
  "Failed to retrieve meteorological telemetries": "আবহাওয়াবিদ্যাগত টেলিমেট্রি সংগ্রহ করা যায়নি",
  "Failed to retrieve notifications": "বিজ্ঞপ্তি সংগ্রহ করা যায়নি",
  "Failed to run recommendation engine": "রিকমেন্ডেশন ইঞ্জিন চালানো যায়নি",
  "Failed to save activity log": "কার্যকলাপ লগ সংরক্ষণ করা যায়নি",
  "Failed to submit arbitration verdict": "সালিশি রায় জমা দেওয়া যায়নি",
  "Failed to update commodity rate": "পণ্যের দর আপডেট করা যায়নি",
  "Failed to update listing status": "তালিকার অবস্থা আপডেট করা যায়নি",
  "Failed to update notification": "বিজ্ঞপ্তি আপডেট করা যায়নি",
  "Failed to update profile": "প্রোফাইল আপডেট করা যায়নি",
  "Failed to update user status": "ইউজারের অবস্থা আপডেট করা যায়নি",
  "Failed to update verification": "যাচাইকরণ আপডেট করা যায়নি",
  "Failed to update verification status": "যাচাইয়ের অবস্থা আপডেট করা যায়নি",
  "Failure": "ব্যর্থ",
  "Farm Description": "খামার বিবরণ",
  "Farm Details": "খামারের বিবরণ",
  "Farm details will be displayed here.": "খামারের বিবরণ এখানে প্রদর্শিত হবে।",
  "Farm Estate Name": "খামার এস্টেটের নাম",
  "Farm Estates & Landholdings": "খামার এস্টেট ও জমি",
  "Farm Land Registry & Cadastral Verification": "খামার ভূমি রেজিস্ট্রি ও ক্যাডাস্ট্রাল যাচাই",
  "Farm Name": "খামারের নাম",
  "Farmer": "কৃষক",
  "Farmer (Production)": "কৃষক (উৎপাদন)",
  "Farmer density and verified land tenure across divisions": "বিভাগ জুড়ে কৃষক ঘনত্ব ও যাচাইকৃত ভূমি মালিকানা",
  "Farmer:": "কৃষক:",
  "Farmers": "কৃষক",
  "Farmers (": "কৃষক (",
  "Farmers, Officers, Labs": "কৃষক, কর্মকর্তা, ল্যাব",
  "Farms adhering to NPK dosage": "এনপিকে ডোজ অনুসরণকারী খামার",
  "Fertilizers": "সার",
  "Field Details": "ক্ষেতের বিবরণ",
  "Field details will be displayed here.": "ক্ষেতের বিবরণ এখানে প্রদর্শিত হবে।",
  "Field Name": "ক্ষেতের নাম",
  "Field plot created successfully": "ক্ষেতের প্লট সফলভাবে তৈরি হয়েছে",
  "file.": "ফাইল।",
  "files": "ফাইল",
  "Flag": "ফ্ল্যাগ",
  "Flagged": "ফ্ল্যাগকৃত",
  "Flagged Price Risks": "ফ্ল্যাগ করা দাম ঝুঁকি",
  "Fleet In Transit": "পথে বহর",
  "Foreign Matter": "বিদেশি ময়লা",
  "Foreign Matter & Chaff:": "বিদেশি ময়লা ও তুষ:",
  "Forgot Password": "পাসওয়ার্ড ভুলে গেছেন?",
  "Fruit": "ফল",
  "Fulfillment": "পরিপূর্ণতা",
  "Full Audit Ledger": "সম্পূর্ণ নিরীক্ষা লেজার",
  "Full Name": "পূর্ণ নাম",
  "Full Official Name": "সম্পূর্ণ দাপ্তরিক নাম",
  "Funds in Arbitration": "সালিশিতে তহবিল",
  "Generate Custom Audit": "কাস্টম নিরীক্ষা তৈরি",
  "Geographic Location / Village": "ভৌগোলিক অবস্থান / গ্রাম",
  "Get in touch with the AgriNova team": "FarmPath টিমের সাথে যোগাযোগ করুন",
  "Go back home": "হোমে ফিরে যান",
  "Government Certified Agronomy & Digital Platform": "সরকার অনুমোদিত কৃষিতত্ত্ব ও ডিজিটাল প্ল্যাটফর্ম",
  "Govt Benchmark Band:": "সরকারি বেঞ্চমার্ক সীমা:",
  "GPS Coords": "জিপিএস স্থানাঙ্ক",
  "GPS monitored freight": "জিপিএস মনিটরড কার্গো",
  "GPS:": "জিপিএস:",
  "Grade A Passed": "গ্রেড এ পাস",
  "Gusty winds of 50-70 km/h with heavy squalls predicted within the next 12 hours...": "আগামী ১২ ঘণ্টায় ৫০-৭০ কিমি/ঘণ্টা বাতাসসহ ভারী ঝড়ের পূর্বাভাস...",
  "Harvest Lot Details": "হার্ভেস্ট লটের বিবরণ",
  "Harvest lot details will be displayed here.": "হার্ভেস্ট লটের বিবরণ এখানে প্রদর্শিত হবে।",
  "Harvest lot recorded in warehouse registry": "গুদাম রেজিস্ট্রিতে হার্ভেস্ট লট রেকর্ড হয়েছে",
  "Held in Escrow": "এসক্রোতে আটক",
  "High": "উচ্চ",
  "High (Outbreak Likely)": "উচ্চ (প্রাদুর্ভাব সম্ভাব্য)",
  "Hub:": "হাব:",
  "ID:": "আইডি:",
  "Immutable event logs of administrative approvals, credential changes, and system broadcasts": "প্রশাসনিক অনুমোদন, পরিচয়পত্র পরিবর্তন ও সিস্টেম সম্প্রচারের অপরিবর্তনীয় ইভেন্ট লগ",
  "Immutable System & Security Audit Ledger": "অপরিবর্তনীয় সিস্টেম ও নিরাপত্তা নিরীক্ষা লেজার",
  "In Active Mediation": "সক্রিয় মধ্যস্থতায়",
  "In arbitration queue": "সালিশি সারিতে",
  "Included": "অন্তর্ভুক্ত",
  "Input Marketplace": "ইনপুট মার্কেটপ্লেস",
  "Input Supplier": "ইনপুট সরবরাহকারী",
  "Inspect Cert": "সার্টিফিকেট দেখুন",
  "Inspector in Charge:": "দায়িত্বপ্রাপ্ত পরিদর্শক:",
  "Instant Demo": "ইনস্ট্যান্ট ডেমো",
  "Institutional & Mandi": "প্রাতিষ্ঠানিক ও মণ্ডী",
  "Interactive Syllabus & Video Modules": "ইন্টারেক্টিভ সিলেবাস ও ভিডিও মডিউল",
  "IP Address": "আইপি ঠিকানা",
  "IP:": "আইপি:",
  "Irrigation": "সেচ",
  "Irrigation & Water": "সেচ ও পানি",
  "Irrigation Timing": "সেচের সময়",
  "Issue Weather Alert": "আবহাওয়া সতর্কতা জারি",
  "Issued:": "প্রকাশিত:",
  "Issuing Body:": "প্রকাশকারী সংস্থা:",
  "kg": "কেজি",
  "kg (": "কেজি (",
  "kg/ac": "কেজি/একর",
  "Khatian:": "খতিয়ান:",
  "km/h": "কিমি/ঘণ্টা",
  "Lab Moisture & Grades": "ল্যাব আর্দ্রতা ও গ্রেড",
  "Lab Quality Batch Reports exported as PDF": "ল্যাব মান ব্যাচ রিপোর্ট পিডিএফ হিসেবে এক্সপোর্ট হয়েছে",
  "Lab:": "ল্যাব:",
  "Lakh": "লাখ",
  "Land Area (acres)": "জমির পরিমাণ (একর)",
  "Language Selector": "ভাষা নির্বাচক",
  "Latitude": "অক্ষাংশ",
  "Lead Agronomist:": "প্রধান কৃষিবিদ:",
  "Learning": "শেখা",
  "Lesson progress recorded! Knowledge badge updated.": "পাঠের অগ্রগতি রেকর্ড হয়েছে! নলেজ ব্যাজ আপডেট হয়েছে।",
  "lessons": "পাঠ",
  "Listed:": "তালিকাভুক্ত:",
  "Listing Approvals": "তালিকা অনুমোদন",
  "Live Cargo Temp": "লাইভ কার্গো তাপমাত্রা",
  "Live Escrow Audited:": "লাইভ এসক্রো নিরীক্ষিত:",
  "Login": "লগইন",
  "Logistics": "লজিস্টিকস",
  "Longitude": "দ্রাঘিমাংশ",
  "Looking for a starting point or more instructions? Head over to": "শুরুর বিন্দু বা আরও নির্দেশনা খুঁজছেন? দেখুন",
  "Lot Code:": "লট কোড:",
  "Lots": "লট",
  "Low": "নিম্ন",
  "Low (Advisory Info)": "নিম্ন (পরামর্শমূলক তথ্য)",
  "Machine Learning Agronomy Model • Confidence": "মেশিন লার্নিং কৃষিতত্ত্ব মডেল • আত্মবিশ্বাস",
  "Macro Agro Intelligence": "ম্যাক্রো কৃষি বুদ্ধিমত্তা",
  "Macro telemetry encompassing national crop yields, fertilizer optimization index, and regional soil chemistry.": "জাতীয় ফসল ফলন, সার অপ্টিমাইজেশন সূচক ও আঞ্চলিক মাটি রসায়ন অন্তর্ভুক্ত ম্যাক্রো টেলিমেট্রি।",
  "Manage Products": "পণ্য ব্যবস্থাপনা",
  "Managing": "ব্যবস্থাপনায়",
  "Marketplace": "মার্কেটপ্লেস",
  "Maturity (Days)": "পরিপক্বতা (দিন)",
  "Maturity Days": "পরিপক্বতার দিন",
  "MB": "এমবি",
  "MB (Indexed Vector PDF)": "এমবি (ইনডেক্সড ভেক্টর পিডিএফ)",
  "Mediation In Progress": "মধ্যস্থতা চলমান",
  "Medium": "মাঝারি",
  "Medium (Precautionary)": "মাঝারি (সতর্কতামূলক)",
  "Meteorological Description": "আবহাওয়াবিদ্যাগত বিবরণ",
  "Metric Tons": "মেট্রিক টন",
  "Microclimate & Disease Risk Radar": "মাইক্রোক্লাইমেট ও রোগ ঝুঁকি রাডার",
  "mins": "মিনিট",
  "mm rain": "মিমি বৃষ্টি",
  "Mobile Number": "মোবাইল নম্বর",
  "Model diagnosis on soil chemistry, seasonal suitability, and moisture retention": "মাটির রসায়ন, মৌসুমি উপযোগিতা ও আর্দ্রতা ধারণে মডেল নির্ণয়",
  "modules finished": "মডিউল সমাপ্ত",
  "Mohiuddin Khan Agricultural Ecosystem": "মোহিউদ্দিন খান কৃষি ইকোসিস্টেম",
  "Moisture <14.0%": "আর্দ্রতা <১৪.০%",
  "Moisture Content:": "আর্দ্রতা:",
  "Mokam:": "মোকাম:",
  "Monitor institutional agricultural procurement contracts, delivery status, and escrow releases.": "প্রাতিষ্ঠানিক কৃষি সংগ্রহ চুক্তি, ডেলিভারি অবস্থা ও এসক্রো মুক্তি মনিটর করুন।",
  "Monitored Acreage": "নিরীক্ষিত জমি",
  "Monitored Cropland": "নিরীক্ষিত ফসলি জমি",
  "Mouza & Khatian": "মৌজা ও খতিয়ান",
  "MT": "মেট্রিক টন",
  "MT)": "মেট্রিক টন)",
  "National Agritech": "ন্যাশনাল এগ্রিটেক",
  "National Agritech Intelligence & Macro Reports": "জাতীয় এগ্রিটেক বুদ্ধিমত্তা ও ম্যাক্রো রিপোর্ট",
  "National Agro-Freight & Cold Chain Logistics Fleet": "জাতীয় কৃষি-মালবাহী ও কোল্ড চেইন লজিস্টিক বহর",
  "National Agromet & Flash-Flood Broadcast Terminal": "জাতীয় কৃষি-আবহাওয়া ও আকস্মিক বন্যা সম্প্রচার টার্মিনাল",
  "National Agronomic Platform & Macro Analytics": "জাতীয় কৃষিতত্ত্ব প্ল্যাটফর্ম ও ম্যাক্রো বিশ্লেষণ",
  "National Crop Acreage Allocation": "জাতীয় ফসলি জমি বরাদ্দ",
  "National ID (NID)": "জাতীয় পরিচয়পত্র (এনআইডি)",
  "National Master Crop & Cultivar Catalog": "জাতীয় মাস্টার ফসল ও জাত ক্যাটালগ",
  "National Settlement, Escrow & Payment Gateway": "জাতীয় নিষ্পত্তি, এসক্রো ও পেমেন্ট গেটওয়ে",
  "National Wholesale Commodity Price Benchmarking": "জাতীয় পাইকারি পণ্য মূল্য বেঞ্চমার্কিং",
  "National Wholesale Marketplace Supervision": "জাতীয় পাইকারি মার্কেটপ্লেস তত্ত্বাবধান",
  "National Wholesale Orders & Escrow Audit": "জাতীয় পাইকারি অর্ডার ও এসক্রো নিরীক্ষা",
  "New calendar event added": "নতুন ক্যালেন্ডার ইভেন্ট যোগ হয়েছে",
  "New crop taxon added to national registry": "জাতীয় রেজিস্ট্রিতে নতুন ফসল ট্যাক্সন যোগ হয়েছে",
  "New extension curriculum published": "নতুন এক্সটেনশন কারিকুলাম প্রকাশিত হয়েছে",
  "New farm registered successfully": "নতুন খামার সফলভাবে নিবন্ধিত হয়েছে",
  "New user account registered and verified": "নতুন ইউজার অ্যাকাউন্ট নিবন্ধিত ও যাচাইকৃত হয়েছে",
  "NID:": "এনআইডি:",
  "No active crop cycles.": "কোনো সক্রিয় ফসল চক্র নেই।",
  "No deliveries in progress.": "চলমান কোনো ডেলিভারি নেই।",
  "No demands posted yet.": "এখনো কোনো চাহিদা পোস্ট হয়নি।",
  "No orders yet.": "এখনো কোনো অর্ডার নেই।",
  "No payment records yet.": "এখনো কোনো পেমেন্ট রেকর্ড নেই।",
  "No products listed yet.": "এখনো কোনো পণ্য তালিকাভুক্ত হয়নি।",
  "No quality requests yet.": "এখনো কোনো মান যাচাইয়ের অনুরোধ নেই।",
  "Notification marked as read": "বিজ্ঞপ্তি পড়া হিসেবে চিহ্নিত হয়েছে",
  "Nutrient Management": "পুষ্টি ব্যবস্থাপনা",
  "Nutrient Parameter": "পুষ্টি প্যারামিটার",
  "of": "মোট",
  "Oilseed": "তেলবীজ",
  "On Route": "পথে",
  "Open - Under Review": "খোলা - পর্যালোচনাধীন",
  "Opened:": "খোলা:",
  "Operating Region / Jurisdiction": "কর্মক্ষেত্র / এখতিয়ার",
  "Optimal Soil pH": "সর্বোত্তম মাটি পিএইচ",
  "or the": "অথবা",
  "Order Code": "অর্ডার কোড",
  "Order Details": "অর্ডারের বিবরণ",
  "Order details will be displayed here.": "অর্ডারের বিবরণ এখানে প্রদর্শিত হবে।",
  "Order Reference:": "অর্ডার রেফারেন্স:",
  "Order:": "অর্ডার:",
  "Orders": "অর্ডার",
  "Out of DAM corridor": "ডিএএম করিডোরের বাইরে",
  "Oversee vocational agricultural masterclasses, regional participation, and certification pass rates.": "বৃত্তিমূলক কৃষি মাস্টারক্লাস, আঞ্চলিক অংশগ্রহণ ও সার্টিফিকেশন পাসের হার তত্ত্বাবধান করুন।",
  "Owner:": "মালিক:",
  "Page Not Found": "পেজ পাওয়া যায়নি",
  "Passed (Grade A/B)": "পাস (গ্রেড এ/বি)",
  "Password": "পাসওয়ার্ড",
  "Payment Channel": "পেমেন্ট চ্যানেল",
  "Payment settlement batch exported to CSV": "পেমেন্ট নিষ্পত্তির ব্যাচ সিএসভিতে এক্সপোর্ট হয়েছে",
  "Payments": "পেমেন্ট",
  "pending": "অপেক্ষমাণ",
  "Pending Admin Dual-Sign": "এডমিন ডুয়াল-সাইন অপেক্ষমাণ",
  "Pending Approval": "অনুমোদন অপেক্ষমাণ",
  "Pending Audit": "নিরীক্ষা অপেক্ষমাণ",
  "Pending Land Approvals": "ভূমি অনুমোদন অপেক্ষমাণ",
  "Pending Review": "রিভিউ চলমান",
  "Pending Verification": "যাচাই অপেক্ষমাণ",
  "Pending Verifications": "যাচাই অপেক্ষমাণ",
  "Pest & Blight Radar": "কীট ও ব্লাইট রাডার",
  "Pest Alert": "কীট সতর্কতা",
  "Pest Management": "কীট ব্যবস্থাপনা",
  "Pest Vulnerabilities": "কীট ঝুঁকি",
  "Pest Vulnerabilities (comma-separated)": "কীট ঝুঁকি (কমা দ্বারা পৃথক)",
  "Ping GPS Sensors": "জিপিএস সেন্সর পরীক্ষা",
  "Plaintiff:": "বাদী:",
  "Platform Administrator": "প্ল্যাটফর্ম প্রশাসক",
  "Platform Admins": "প্ল্যাটফর্ম এডমিন",
  "Platform Settings": "প্ল্যাটফর্ম সেটিংস",
  "Platform settings will be displayed here.": "প্ল্যাটফর্ম সেটিংস এখানে প্রদর্শিত হবে।",
  "Please keep at least 2 crops selected for meaningful comparison": "অর্থপূর্ণ তুলনার জন্য কমপক্ষে ২টি ফসল নির্বাচন রাখুন",
  "Plots:": "প্লট:",
  "Post Demand": "চাহিদা পোস্ট করুন",
  "Post-Harvest": "ফসলোত্তর",
  "Post-Harvest Grain & Produce Quality Assurance": "ফসলোত্তর শস্য ও ফলনের মান নিশ্চয়তা",
  "ppm": "পিপিএম",
  "ppm (Safe <20 ppm)": "পিপিএম (নিরাপদ <২০ পিপিএম)",
  "Precision Drip Grid": "প্রিসিশন ড্রিপ গ্রিড",
  "Precision satellite mapped": "প্রিসিশন স্যাটেলাইট ম্যাপিং",
  "Predicted Yield Potential": "পূর্বাভাসিত ফলন সম্ভাবনা",
  "Prescriptive Fertilizer Dosing Schedule": "নির্দেশিত সার ডোজ সময়সূচি",
  "Preview": "প্রিভিউ",
  "Price per kg": "প্রতি কেজি দাম",
  "Primary Irrigation Infrastructure": "প্রাথমিক সেচ অবকাঠামো",
  "Processing": "প্রকেসিং",
  "Produce & Volume": "ফলন ও পরিমাণ",
  "Produce Marketplace": "ফলন মার্কেটপ্লেস",
  "Produce:": "ফলন:",
  "Producer Farmer:": "উৎপাদক কৃষক:",
  "Product management will be displayed here.": "পণ্য ব্যবস্থাপনা এখানে প্রদর্শিত হবে।",
  "Product Name": "পণ্যের নাম",
  "Profile updated successfully": "প্রোফাইল সফলভাবে আপডেট হয়েছে",
  "Projected Yield": "প্রক্ষেপিত ফলন",
  "Protected by digital escrow": "ডিজিটাল এসক্রো দ্বারা সুরক্ষিত",
  "Provision New Account": "নতুন অ্যাকাউন্ট প্রদান",
  "Provision Platform User Account": "প্ল্যাটফর্ম ইউজার অ্যাকাউন্ট প্রদান",
  "Publication Date:": "প্রকাশের তারিখ:",
  "Publication Status": "প্রকাশের অবস্থা",
  "Publish & Broadcast": "প্রকাশ ও সম্প্রচার",
  "Publish Curriculum": "কারিকুলাম প্রকাশ",
  "Publish Extension Course Curriculum": "এক্সটেনশন কোর্স কারিকুলাম প্রকাশ",
  "Publish New Advisory": "নতুন পরামর্শ প্রকাশ",
  "Published (Open Enrollment)": "প্রকাশিত (খোলা তালিকাভুক্তি)",
  "Pulse": "ডাল",
  "Purpose": "উদ্দেশ্য",
  "Quality Request Details": "মান যাচাইয়ের অনুরোধের বিবরণ",
  "Quality request details will be displayed here.": "মান যাচাইয়ের অনুরোধের বিবরণ এখানে প্রদর্শিত হবে।",
  "Quality Verification": "মান যাচাই",
  "Quantity (kg)": "পরিমাণ (কেজি)",
  "Quantity:": "পরিমাণ:",
  "Quarterly harvest yield forecasting, soil chemistry surveys, pesticide drift assessments, and subsidy audits.": "ত্রৈমাসিক ফসল ফলন পূর্বাভাস, মাটি রসায়ন জরিপ, কীটনাশক বিচ্ছুরণ মূল্যায়ন ও ভর্তুকি নিরীক্ষা।",
  "Rainfed": "বৃষ্টিনির্ভর",
  "Re-drying recommended": "পুনরায় শুকানোর পরামর্শ",
  "Ready to execute this crop recommendation?": "এই ফসলের সুপারিশ কার্যকর করতে প্রস্তুত?",
  "Real-time IoT reefer telemetry, temperature logger compliance, and inter-district freight dispatch monitoring.": "রিয়েল-টাইম আইওটি রিফার টেলিমেট্রি, তাপমাত্রা লগার কমপ্লায়েন্স ও আন্তঃজেলা মালবাহী ডিসপ্যাচ মনিটরিং।",
  "Real-time push broadcasting of severe weather, pest outbreaks, and heatwave warnings to farmer dashboards and SMS.": "কৃষকের ড্যাশবোর্ড ও এসএমএসে তীব্র আবহাওয়া, কীট প্রাদুর্ভাব ও তাপপ্রবাহ সতর্কতার রিয়েল-টাইম পুশ সম্প্রচার।",
  "Real-time test reading compared against optimal baseline thresholds": "অনুকূল বেসলাইন থ্রেশহোল্ডের সাথে রিয়েল-টাইম পরীক্ষার মান তুলনা",
  "Reason:": "কারণ:",
  "Recent deed & GPS submissions": "সাম্প্রতিক দলিল ও জিপিএস জমাদান",
  "Recent System & Security Audit Ledger": "সাম্প্রতিক সিস্টেম ও নিরাপত্তা নিরীক্ষা লেজার",
  "Recipient & Role": "প্রাপক ও ভূমিকা",
  "Recommendation generated based on soil chemistry": "মাটির রসায়নের ভিত্তিতে সুপারিশ তৈরি হয়েছে",
  "Recommended Agronomic Defense": "প্রস্তাবিত কৃষি প্রতিরোধ ব্যবস্থা",
  "Recommended Field Treatments (one per line)": "প্রস্তাবিত মাঠ-চিকিৎসা (প্রতি লাইনে একটি)",
  "Recommended Season": "প্রস্তাবিত মৌসুম",
  "Record lab moisture re-check, weigher scale slips, or transport IoT logs and specify release verdict...": "ল্যাব আর্দ্রতা পুনঃপরীক্ষা, ওজন স্কেল স্লিপ বা পরিবহন আইওটি লগ রেকর্ড করুন এবং মুক্তির রায় নির্ধারণ করুন...",
  "Refund Escrow to Buyer": "ক্রেতাকে এসক্রো ফেরত",
  "Refunded": "ফেরত",
  "Regional Agro-Ecological Distribution": "আঞ্চলিক কৃষি-পরিবেশগত বণ্টন",
  "Regional moisture labs": "আঞ্চলিক আর্দ্রতা ল্যাব",
  "Regional Productivity & Compliance": "আঞ্চলিক উৎপাদনশীলতা ও কমপ্লায়েন্স",
  "Register": "নিবন্ধন",
  "Register Master Crop Variety": "মাস্টার ফসলের জাত নিবন্ধন",
  "Register New Farm": "নতুন খামার নিবন্ধন",
  "Register New Farm Estate": "নতুন খামার এস্টেট নিবন্ধন",
  "Registered agrarian landholdings and verified farmer density by division": "বিভাগ অনুযায়ী নিবন্ধিত কৃষি জমি এবং যাচাইকৃত কৃষক ঘনত্ব",
  "Registered Farmers": "নিবন্ধিত কৃষক",
  "registered farmers, agronomists, extension officers, and platform operators.": "নিবন্ধিত কৃষক, কৃষিবিদ, এক্সটেনশন অফিসার ও প্ল্যাটফর্ম অপারেটর।",
  "Registered Land:": "নিবন্ধিত জমি:",
  "Reject Record": "রেকর্ড প্রত্যাখ্যান",
  "Rejected": "প্রত্যাখ্যাত",
  "Rejected Lots": "প্রত্যাখ্যাত লট",
  "Release Escrow to Farmer": "কৃষককে এসক্রো মুক্ত",
  "Released to Farmer": "কৃষকের কাছে মুক্ত",
  "Remember your password?": "পাসওয়ার্ড মনে আছে?",
  "Required Field Action": "প্রয়োজনীয় মাঠ-কর্ম",
  "Required Quantity (kg)": "প্রয়োজনীয় পরিমাণ (কেজি)",
  "Resolution Rate": "সমাধানের হার",
  "Resolve buyer-farmer contract conflicts: Quality downgrades, moisture variance, transit spoilage, and payout disputes.": "ক্রেতা-কৃষক চুক্তি বিরোধ সমাধান: মান নিম্নতর, আর্দ্রতা পার্থক্য, পরিবহন ক্ষতি ও পেমেন্ট বিবাদ।",
  "Resolved - Buyer Refunded": "সমাধান - ক্রেতা ফেরতপ্রাপ্ত",
  "Resolved - Farmer Compensated": "সমাধান - কৃষক ক্ষতিপূরণপ্রাপ্ত",
  "Respondent (Defendant):": "বিবাদী:",
  "Retail Price": "খুচরা মূল্য",
  "Revenue & Profitability": "রাজস্ব ও মুনাফা",
  "Risk": "ঝুঁকি",
  "RISK": "ঝুঁকি",
  "Risk Severity Level": "ঝুঁকি তীব্রতার মাত্রা",
  "River/Canal Gravity": "নদী/খাল মাধ্যাকর্ষণ",
  "Role & Region": "ভূমিকা ও অঞ্চল",
  "Save": "সংরক্ষণ",
  "Save Farm": "খামার সংরক্ষণ",
  "Save Farm Estate": "খামার এস্টেট সংরক্ষণ",
  "Save Field": "ক্ষেত সংরক্ষণ",
  "Save to Catalog": "ক্যাটালগে সংরক্ষণ",
  "Search batch code, farmer, lab, or certificate...": "ব্যাচ কোড, কৃষক, ল্যাব বা সার্টিফিকেট খুঁজুন...",
  "Search by action, actor, IP or detail...": "কর্ম, কর্তা, আইপি বা বিবরণ দিয়ে খুঁজুন...",
  "Search by crop or scientific name...": "ফসল বা বৈজ্ঞানিক নামে খুঁজুন...",
  "Search by name, email, NID, or phone...": "নাম, ইমেইল, এনআইডি বা ফোন দিয়ে খুঁজুন...",
  "Search case no, plaintiff, order or reason...": "কেস নম্বর, বাদী, অর্ডার বা কারণ খুঁজুন...",
  "Search consignment, origin, destination, driver...": "কনসাইনমেন্ট, উৎস, গন্তব্য, চালক খুঁজুন...",
  "Search order code, buyer, farmer or produce...": "অর্ডার কোড, ক্রেতা, কৃষক বা ফলন খুঁজুন...",
  "Search produce, farmer, cultivar, or hub...": "ফলন, কৃষক, জাত বা হাব খুঁজুন...",
  "Search report titles, code or findings...": "রিপোর্ট শিরোনাম, কোড বা ফলাফল খুঁজুন...",
  "Search txn ref, recipient, channel or purpose...": "লেনদেন রেফারেন্স, প্রাপক, চ্যানেল বা উদ্দেশ্য খুঁজুন...",
  "Season 2026": "মৌসুম ২০২৬",
  "Season:": "মৌসুম:",
  "Security audit log exported as CSV": "নিরাপত্তা নিরীক্ষা লগ সিএসভি হিসেবে এক্সপোর্ট হয়েছে",
  "Security Classification:": "নিরাপত্তা শ্রেণিবিভাগ:",
  "Seeds": "বীজ",
  "Select Role": "ভূমিকা নির্বাচন",
  "Select Season": "মৌসুম নির্বাচন",
  "Sell your harvested products": "আপনার উৎপাদিত ফসল বিক্রি করুন",
  "Seller:": "বিক্রেতা:",
  "Send Reset Link": "রিসেট লিংক পাঠান",
  "Set up instructor assignment and regional enrollment targets": "প্রশিক্ষক নিয়োগ ও আঞ্চলিক তালিকাভুক্তির লক্ষ্য নির্ধারণ করুন",
  "Settled ✓": "নিষ্পন্ন ✓",
  "Severity": "তীব্রতা",
  "Showing": "দেখানো হচ্ছে",
  "Sign out": "সাইন আউট",
  "Sign Out": "সাইন আউট",
  "Sign out of account": "অ্যাকাউন্ট থেকে সাইন আউট",
  "Simulated agronomic risks and proactive field countermeasures": "সিমুলেটেড কৃষি ঝুঁকি ও সক্রিয় মাঠ প্রতিরোধ ব্যবস্থা",
  "Since": "থেকে",
  "Smart Agriculture & Farm-to-Market Platform": "স্মার্ট কৃষি ও ফার্ম-টু-মার্কেট প্ল্যাটফর্ম",
  "Soil Chemical Deficiencies & Macronutrient Balance": "মাটির রাসায়নিক ঘাটতি ও ম্যাক্রোনিউট্রিয়েন্ট ভারসাম্য",
  "Soil Classification": "মাটির শ্রেণিবিভাগ",
  "Soil Health": "মাটি স্বাস্থ্য",
  "Soil Salinity & NPK": "মাটি লবণাক্ততা ও এনপিকে",
  "Soil Type": "মাটির ধরন",
  "Sold Out": "বিক্রি শেষ",
  "Specify land coordinates, irrigation systems, and soil classification": "জমির স্থানাঙ্ক, সেচ ব্যবস্থা ও মাটির শ্রেণিবিভাগ উল্লেখ করুন",
  "Spray azoxystrobin @ 1ml/L Drain standing water...": "আজক্সিস্ট্রোবিন @ ১ মি.লি./লি. স্প্রে করুন। জমে থাকা পানি নিষ্কাশন করুন...",
  "Spring": "বসন্ত",
  "Sprinkler Set": "স্প্রিংকলার সেট",
  "Standard Yield": "প্রমিত ফলন",
  "Standardized agronomic benchmarks, seasonal calendars, and pest resistance indices for Bangladesh.": "বাংলাদেশের জন্য প্রমাণিত কৃষি বেঞ্চমার্ক, মৌসুমি ক্যালেন্ডার ও কীট প্রতিরোধ সূচক।",
  "Status": "অবস্থা",
  "Status:": "অবস্থা:",
  "Subject Category:": "বিষয় বিভাগ:",
  "Submission Date": "জমার তারিখ",
  "Submitted:": "জমা:",
  "Subsidy Impact": "ভর্তুকির প্রভাব",
  "Success": "সফল",
  "Summer": "গ্রীষ্ম",
  "Supervising regional land registries, DAE extension courses, real-time commodity trading, and agro-met advisories across Bangladesh.": "সারাদেশে আঞ্চলিক ভূমি রেজিস্ট্রি, ডিএই ই এক্সটেনশন কোর্স, রিয়েল-টাইম কমোডিটি ট্রেডিং ও কৃষি-আবহাওয়া পরামর্শ তত্ত্বাবধান করা হচ্ছে।",
  "Suspend harvesting and chemical spraying, secure nursery seedbeds, clear drainage canals...": "ফসল কাটা ও রাসায়নিক স্প্রে স্থগিত করুন, নার্সারি বীজতলা সুরক্ষিত করুন, ড্রেনেজ খাল পরিষ্কার করুন...",
  "Suspended": "স্থগিত",
  "Sync Market Feeds": "মার্কেট ফিড সিঙ্ক",
  "Synthesized by comparing soil telemetry (pH 6.4, N-18kg, P-24kg, K-42kg) with historical regional harvest logs across Bogura district.": "বগুড়া জেলার ঐতিহাসিক আঞ্চলিক ফসল লগের সাথে মাটি টেলিমেট্রি (পিএইচ ৬.৪, N-১৮কেজি, P-২৪কেজি, K-৪২কেজি) তুলনা করে সিন্থেসাইজ করা হয়েছে।",
  "Target Agro-Ecological Region": "লক্ষ্য কৃষি-পরিবেশগত অঞ্চল",
  "Target Crops (comma-separated)": "লক্ষ্য ফসল (কমা দ্বারা পৃথক)",
  "Target Crops:": "লক্ষ্য ফসল:",
  "Target Districts (comma-separated)": "লক্ষ্য জেলা (কমা দ্বারা পৃথক)",
  "Target Entity": "লক্ষ্য সংস্থা",
  "Target Region": "লক্ষ্য অঞ্চল",
  "Task status updated": "কাজের স্ট্যাটাস আপডেট হয়েছে",
  "Temperature within band": "তাপমাত্রা সীমার মধ্যে",
  "Templates": "টেমপ্লেট",
  "Through licensed mokams": "লাইসেন্সপ্রাপ্ত মোকামের মাধ্যমে",
  "Timestamp": "টাইমস্ট্যাম্প",
  "to": "থেকে",
  "To get started, edit the": "শুরু করতে সম্পাদনা করুন",
  "Toggle completed": "সম্পন্ন টগল",
  "Toggle Navigation Menu": "নেভিগেশন মেনু টগল",
  "Toggle task": "টাস্ক টগল",
  "Tons": "টন",
  "Tools & Equipment": "সরঞ্জাম ও যন্ত্রপাতি",
  "Total Acres": "মোট একর",
  "Total Contract Value": "মোট চুক্তি মূল্য",
  "Total Disputes Logged": "মোট নথিভুক্ত বিবাদ",
  "Total Escrow Fund:": "মোট এসক্রো তহবিল:",
  "Total Farmers Enrolled": "মোট নিবন্ধিত কৃষক",
  "Total Land Area (Acres)": "মোট জমির পরিমাণ (একর)",
  "Total Lot Value:": "মোট লট মূল্য:",
  "Total Lots Tested": "মোট পরীক্ষিত লট",
  "Total of": "মোট",
  "Total Orders Tracked": "মোট ট্র্যাককৃত অর্ডার",
  "Total Settled Volume": "মোট নিষ্পন্ন ভলিউম",
  "Total Traded Volume": "মোট লেনদেন ভলিউম",
  "Track Unit": "ইউনিট ট্র্যাক করুন",
  "Traded Volume": "লেনদেন ভলিউম",
  "Traffic / Weather Delays": "ট্রাফিক / আবহাওয়া বিলম্ব",
  "Training Course Curriculum Oversight": "প্রশিক্ষণ কোর্স কারিকুলাম তত্ত্বাবধান",
  "Transaction Ref": "লেনদেন রেফারেন্স",
  "Transmit Push Broadcast": "পুশ সম্প্রচার প্রেরণ",
  "TREND": "প্রবণতা",
  "Tribunal Findings & Resolution:": "ট্রাইবুনালের সিদ্ধান্ত ও সমাধান:",
  "Type your question...": "আপনার প্রশ্ন লিখুন...",
  "Upazila & District": "উপজেলা ও জেলা",
  "Updated:": "আপডেট:",
  "Urgent": "জরুরি",
  "Urgent (Emergency Action)": "জরুরি (জরুরি পদক্ষেপ)",
  "User Identity": "ইউজার পরিচয়",
  "User Identity & Role Access Governance": "ইউজার পরিচয় ও ভূমিকা অ্যাক্সেস শাসন",
  "Valid Until:": "বৈধ পর্যন্ত:",
  "Variety:": "জাত:",
  "Vegetable": "সবজি",
  "Verification": "যাচাইকরণ",
  "Verified": "যাচাইকৃত",
  "Verify against the Land Revenue Portal (e-Namjari & Khatian registry)...": "ভূমি রাজস্ব পোর্টালে যাচাই করুন (ই-নামজারি ও খতিয়ান রেজিস্ট্রি)...",
  "Verify Checksum ✓": "চেকসাম যাচাই ✓",
  "View All (": "সব দেখুন (",
  "View Details": "বিস্তারিত দেখুন",
  "View notifications": "বিজ্ঞপ্তি দেখুন",
  "vs": "বনাম",
  "W/m² Insolation": "W/m² সৌর বিকিরণ",
  "Warning": "সতর্ক",
  "Warning (Moderate Agronomic Hazard)": "সতর্কতা (মাঝারি কৃষি বিপদ)",
  "Water Source": "পানি উৎস",
  "Water Supply Source": "পানি সরবরাহের উৎস",
  "Weather Advisory": "আবহাওয়া পরামর্শ",
  "Weekly Market Volume": "সাপ্তাহিক বাজার ভলিউম",
  "Welcome to AgriNova": "FarmPath-তে স্বাগতম",
  "Wholesale Range": "পাইকারি সীমা",
  "Wholesale Trade Grievance & Escrow Arbitration": "পাইকারি বাণিজ্য অভিযোগ ও এসক্রো সালিশি",
  "Will be pushed to all farmers growing target crops in selected districts": "নির্বাচিত জেলায় লক্ষ্য ফসল চাষকারী সব কৃষককে পুশ করা হবে",
  "Winter": "শীত",
  "Within 48 hours SLA": "৪৮ ঘণ্টার এসএলএ-র মধ্যে",
  "Yield (Kg / Acre)": "ফলন (কেজি / একর)",
  "Yield Forecast": "ফলন পূর্বাভাস",
  "You can compare up to 4 crops simultaneously": "একসাথে সর্বোচ্চ ৪টি ফসল তুলনা করতে পারবেন",
  "Your": "আপনার",

  // Error Pages
  "Lost in the farm fields!": "হারিয়ে গেছে খামারের পথ!",
  "Looks like this page wandered off into the crops. Don't worry, let's head back home!": "মনে হচ্ছে এই পাতাটি খামারের গুল্মে হারিয়ে গেছে। চিন্তা করবেন না, আসুন ঘরে ফিরে যাই!",
  "The tractor broke down!": "ট্র্যাক্টর বিগড়ে গেছে!",
  "Something went wrong on our end. We're fixing it, please hold on.": "সার্ভারে কিছু সমস্যা হয়েছে। আমরা মেরামত করছি, অপেক্ষা করুন।",
  "Something went wrong...": "কিছু একটা ভুল হয়েছে...",
  "An unexpected error occurred. Try again or head back to the homepage.": "একটি অপ্রত্যাশিত সমস্যা ঘটেছে। আবার চেষ্টা করুন অথবা হোমে ফিরে যান।",
  "Go Back Home": "হোমে ফিরে যান",
  "Try Again": "আবার চেষ্টা করুন",
  "Continue with Google": "গুগল দিয়ে চালিয়ে যান",
  "Continue with GitHub": "গিটহাব দিয়ে চালিয়ে যান",
  "Profile": "প্রোফাইল",
  "Personal Information": "ব্যক্তিগত তথ্য",
  "Phone Number": "মোবাইল নম্বর",
  "Address": "ঠিকানা",
  "Save Changes": "পরিবর্তন সংরক্ষণ করুন",
  "Saved!": "সংরক্ষিত হয়েছে!",
  "Your address": "আপনার ঠিকানা",
};
